title: Boubacar Diallo
logo: /img/nny.jpg
description: >
  Portfolio Data Scientist IA, Data Scientist & Analyst,
  Formation et projets en intelligence artificielle et data.
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
